-- Generated by fq_metrics.measures.views_sql; do not edit by hand.
-- Each measure has an all-time and trailing-30-day row. Empty denominators yield NULL.

DROP VIEW IF EXISTS first_pass_rate;
CREATE VIEW first_pass_rate AS
WITH windows(window,start,end) AS (VALUES ('30_days',datetime('now','-30 days'),datetime('now')),('all_time',NULL,NULL))
SELECT w.window,
  1.0 * SUM(CASE WHEN o.accepted=1 AND NOT EXISTS (
    SELECT 1 FROM interventions i WHERE i.issue=a.issue
      AND i.at >= a.dispatched_at AND i.at <= COALESCE(a.ended_at,w.end,datetime('now'))
  ) THEN 1 ELSE 0 END) / NULLIF(COUNT(a.invocation_id),0) AS value
FROM windows w
LEFT JOIN attempts a ON (w.start IS NULL OR a.dispatched_at >= w.start) AND (w.end IS NULL OR a.dispatched_at <= w.end)
LEFT JOIN outcomes o ON o.pr_number=a.pr_number
GROUP BY w.window;

DROP VIEW IF EXISTS attempts_per_accept;
CREATE VIEW attempts_per_accept AS
WITH windows(window,start,end) AS (VALUES ('30_days',datetime('now','-30 days'),datetime('now')),('all_time',NULL,NULL))
SELECT w.window, 1.0 * COUNT(DISTINCT a.invocation_id) /
  NULLIF(COUNT(DISTINCT CASE WHEN o.accepted=1 THEN a.issue END),0) AS value
FROM windows w
LEFT JOIN attempts a ON (w.start IS NULL OR a.dispatched_at >= w.start) AND (w.end IS NULL OR a.dispatched_at <= w.end)
LEFT JOIN outcomes o ON o.pr_number=a.pr_number
GROUP BY w.window;

DROP VIEW IF EXISTS touch_per_accept;
CREATE VIEW touch_per_accept AS
WITH windows(window,start,end) AS (VALUES ('30_days',datetime('now','-30 days'),datetime('now')),('all_time',NULL,NULL)),
totals AS (
  SELECT w.window,o.issue,SUM(COALESCE(i.minutes,0)) minutes
  FROM windows w
  JOIN attempts a ON (w.start IS NULL OR a.dispatched_at >= w.start) AND (w.end IS NULL OR a.dispatched_at <= w.end)
  JOIN outcomes o ON o.pr_number=a.pr_number AND o.accepted=1
  JOIN interventions i ON i.issue=o.issue
  GROUP BY w.window,o.issue
), ranked AS (
  SELECT window,minutes,ROW_NUMBER() OVER(PARTITION BY window ORDER BY minutes) n,
    COUNT(*) OVER(PARTITION BY window) count FROM totals
), medians AS (
  SELECT window,AVG(minutes) value FROM ranked
  WHERE n IN ((count+1)/2,(count+2)/2) GROUP BY window
)
SELECT w.window,m.value FROM windows w LEFT JOIN medians m USING(window);

DROP VIEW IF EXISTS mtbi;
CREATE VIEW mtbi AS
WITH windows(window,start,end) AS (VALUES ('30_days',datetime('now','-30 days'),datetime('now')),('all_time',NULL,NULL)),
gaps AS (
  SELECT w.window,
    (julianday(i.at)-julianday(LAG(i.at) OVER(PARTITION BY w.window ORDER BY i.at)))*24.0 hours
  FROM windows w JOIN interventions i ON (w.start IS NULL OR i.at >= w.start) AND (w.end IS NULL OR i.at <= w.end)
), means AS (
  SELECT window,AVG(hours) value FROM gaps WHERE hours IS NOT NULL GROUP BY window
)
SELECT w.window,m.value FROM windows w LEFT JOIN means m USING(window);

DROP VIEW IF EXISTS correction_ratio;
CREATE VIEW correction_ratio AS
WITH windows(window,start,end) AS (VALUES ('30_days',datetime('now','-30 days'),datetime('now')),('all_time',NULL,NULL)),
corrections AS (
  SELECT w.window,COALESCE(SUM(c.additions+c.deletions),0) loc FROM windows w
  LEFT JOIN corrective_commits c ON (w.start IS NULL OR c.at >= w.start) AND (w.end IS NULL OR c.at <= w.end) GROUP BY w.window
), agents AS (
  SELECT w.window,COALESCE(SUM(p.additions+p.deletions),0) loc FROM windows w
  LEFT JOIN pull_requests p ON p.agent_authored=1 AND (w.start IS NULL OR p.merged_at >= w.start) AND (w.end IS NULL OR p.merged_at <= w.end) GROUP BY w.window
)
SELECT c.window,1.0*c.loc/NULLIF(a.loc,0) AS value
FROM corrections c JOIN agents a USING(window);

DROP VIEW IF EXISTS cost_per_attempt;
CREATE VIEW cost_per_attempt AS
WITH windows(window,start,end) AS (VALUES ('30_days',datetime('now','-30 days'),datetime('now')),('all_time',NULL,NULL))
SELECT w.window,SUM(a.total_cost)/NULLIF(COUNT(a.invocation_id),0) AS value
FROM windows w LEFT JOIN attempts a ON (w.start IS NULL OR a.dispatched_at >= w.start) AND (w.end IS NULL OR a.dispatched_at <= w.end) GROUP BY w.window;

DROP VIEW IF EXISTS cost_per_accepted_change;
CREATE VIEW cost_per_accepted_change AS
WITH windows(window,start,end) AS (VALUES ('30_days',datetime('now','-30 days'),datetime('now')),('all_time',NULL,NULL))
SELECT w.window,SUM(CASE WHEN o.accepted=1 THEN a.total_cost END) /
  NULLIF(COUNT(DISTINCT CASE WHEN o.accepted=1 THEN a.issue END),0) AS value
FROM windows w
LEFT JOIN attempts a ON (w.start IS NULL OR a.dispatched_at >= w.start) AND (w.end IS NULL OR a.dispatched_at <= w.end)
LEFT JOIN outcomes o ON o.pr_number=a.pr_number
GROUP BY w.window;
