"""Canonical SQL definitions for windowed ladder measures and their views."""

from __future__ import annotations

import sqlite3
from datetime import datetime

WINDOW_PREDICATE = "({start} IS NULL OR {column} >= {start}) AND ({end} IS NULL OR {column} <= {end})"

MEASURE_QUERIES = {
    "first_pass_rate": """
SELECT w.window,
  1.0 * SUM(CASE WHEN o.accepted=1 AND NOT EXISTS (
    SELECT 1 FROM interventions i WHERE i.issue=a.issue
      AND i.at >= a.dispatched_at AND i.at <= COALESCE(a.ended_at,w.end,datetime('now'))
  ) THEN 1 ELSE 0 END) / NULLIF(COUNT(a.invocation_id),0) AS value
FROM windows w
LEFT JOIN attempts a ON {attempt_window}
LEFT JOIN outcomes o ON o.pr_number=a.pr_number
GROUP BY w.window""",
    "attempts_per_accept": """
SELECT w.window, 1.0 * COUNT(DISTINCT a.invocation_id) /
  NULLIF(COUNT(DISTINCT CASE WHEN o.accepted=1 THEN a.issue END),0) AS value
FROM windows w
LEFT JOIN attempts a ON {attempt_window}
LEFT JOIN outcomes o ON o.pr_number=a.pr_number
GROUP BY w.window""",
    "touch_per_accept": """
totals AS (
  SELECT w.window,o.issue,SUM(COALESCE(i.minutes,0)) minutes
  FROM windows w
  JOIN attempts a ON {attempt_window}
  JOIN outcomes o ON o.pr_number=a.pr_number AND o.accepted=1
  JOIN interventions i ON i.issue=o.issue
  GROUP BY w.window,o.issue
), ranked AS (
  SELECT window,minutes,ROW_NUMBER() OVER(PARTITION BY window ORDER BY minutes) n,
    COUNT(*) OVER(PARTITION BY window) count FROM totals
), medians AS (
  SELECT window,AVG(minutes) value FROM ranked
  WHERE n IN ((count+1)/2,(count+2)/2) GROUP BY window
)
SELECT w.window,m.value FROM windows w LEFT JOIN medians m USING(window)""",
    "mtbi": """
gaps AS (
  SELECT w.window,
    (julianday(i.at)-julianday(LAG(i.at) OVER(PARTITION BY w.window ORDER BY i.at)))*24.0 hours
  FROM windows w JOIN interventions i ON {intervention_window}
), means AS (
  SELECT window,AVG(hours) value FROM gaps WHERE hours IS NOT NULL GROUP BY window
)
SELECT w.window,m.value FROM windows w LEFT JOIN means m USING(window)""",
    "correction_ratio": """
corrections AS (
  SELECT w.window,COALESCE(SUM(c.additions+c.deletions),0) loc FROM windows w
  LEFT JOIN corrective_commits c ON {correction_window} GROUP BY w.window
), agents AS (
  SELECT w.window,COALESCE(SUM(p.additions+p.deletions),0) loc FROM windows w
  LEFT JOIN pull_requests p ON p.agent_authored=1 AND {merge_window} GROUP BY w.window
)
SELECT c.window,1.0*c.loc/NULLIF(a.loc,0) AS value
FROM corrections c JOIN agents a USING(window)""",
    "cost_per_attempt": """
SELECT w.window,SUM(a.total_cost)/NULLIF(COUNT(a.invocation_id),0) AS value
FROM windows w LEFT JOIN attempts a ON {attempt_window} GROUP BY w.window""",
    "cost_per_accepted_change": """
SELECT w.window,SUM(CASE WHEN o.accepted=1 THEN a.total_cost END) /
  NULLIF(COUNT(DISTINCT CASE WHEN o.accepted=1 THEN a.issue END),0) AS value
FROM windows w
LEFT JOIN attempts a ON {attempt_window}
LEFT JOIN outcomes o ON o.pr_number=a.pr_number
GROUP BY w.window""",
}

REPORT_KEYS = {
    "first_pass_rate": "first_pass_rate",
    "attempts_per_accept": "attempts_per_accept",
    "touch_per_accept": "touch_per_accept_minutes",
    "mtbi": "mtbi_hours",
    "correction_ratio": "correction_ratio",
    "cost_per_attempt": "cost_per_attempt",
    "cost_per_accepted_change": "cost_per_accepted_change",
}


def _query(body: str) -> str:
    predicates = {
        "attempt_window": WINDOW_PREDICATE.format(
            start="w.start", end="w.end", column="a.dispatched_at"),
        "intervention_window": WINDOW_PREDICATE.format(
            start="w.start", end="w.end", column="i.at"),
        "correction_window": WINDOW_PREDICATE.format(
            start="w.start", end="w.end", column="c.at"),
        "merge_window": WINDOW_PREDICATE.format(
            start="w.start", end="w.end", column="p.merged_at"),
    }
    return body.format(**predicates)


def _statement(windows: str, body: str) -> str:
    separator = "" if body.lstrip().startswith("SELECT") else ","
    return windows + separator + body


def measures(db: sqlite3.Connection, start: datetime, end: datetime) -> dict[str, float | None]:
    """Evaluate every canonical measure for one inclusive window."""
    window = "WITH windows(window,start,end) AS (VALUES ('report',?,?))"
    result: dict[str, float | None] = {}
    for view, body in MEASURE_QUERIES.items():
        row = db.execute(_statement(window, _query(body)), (start.isoformat(), end.isoformat())).fetchone()
        value = row[1]
        result[REPORT_KEYS[view]] = float(value) if value is not None else None
    return result


def views_sql() -> str:
    """Render the checked-in SQLite views from the canonical query bodies."""
    chunks = ["-- Generated by fq_metrics.measures.views_sql; do not edit by hand.\n"
              "-- Each measure has an all-time and trailing-30-day row. Empty denominators yield NULL."]
    windows = ("WITH windows(window,start,end) AS (VALUES "
               "('30_days',datetime('now','-30 days'),datetime('now')),"
               "('all_time',NULL,NULL))")
    for name, body in MEASURE_QUERIES.items():
        chunks.append(f"DROP VIEW IF EXISTS {name};\nCREATE VIEW {name} AS\n"
                      f"{_statement(windows, _query(body))};")
    return "\n\n".join(chunks) + "\n"


if __name__ == "__main__":
    print(views_sql(), end="")
