#!/usr/bin/env python3
"""Render cargo-audit JSON and deny.toml policy as a PR comment."""

import json
import sys
import tomllib
from pathlib import Path

MARKER = "<!-- dependency-audit -->"
KINDS = ("unmaintained", "unsound", "yanked")


def cell(value: object) -> str:
    text = str(value or "—").replace("|", "\\|").replace("\n", " ")
    return text


def finding_row(item: dict) -> str:
    advisory = item.get("advisory", {})
    package = item.get("package", {})
    patched = item.get("versions", {}).get("patched", [])
    fixed = ", ".join(patched) if patched else "—"
    return "| {} | {} | {} | {} | {} |".format(
        cell(advisory.get("id")),
        cell(package.get("name") or advisory.get("package")),
        cell(package.get("version")),
        cell(fixed),
        cell(advisory.get("title")),
    )


def table(items: list[dict]) -> list[str]:
    if not items:
        return ["_None._"]
    return [
        "| ID | crate | version | fixed in | title |",
        "|---|---|---|---|---|",
        *(finding_row(item) for item in items),
    ]


def main() -> int:
    if len(sys.argv) != 4:
        raise SystemExit("usage: audit-comment.py <audit.json> <deny.toml> <deny-status>")

    notes: list[str] = []
    try:
        audit = json.loads(Path(sys.argv[1]).read_text())
    except (OSError, json.JSONDecodeError) as error:
        audit = {}
        notes.append(f"cargo-audit output could not be parsed: `{cell(error)}`")

    try:
        policy = tomllib.loads(Path(sys.argv[2]).read_text())
        ignores = policy.get("advisories", {}).get("ignore", [])
    except (OSError, tomllib.TOMLDecodeError) as error:
        ignores = []
        notes.append(f"deny.toml could not be parsed: `{cell(error)}`")

    vulnerabilities = audit.get("vulnerabilities", {}).get("list", [])
    warnings = audit.get("warnings", {})
    lines = [
        MARKER,
        "## Dependency audit",
        "",
        "Advisory report for the dependency graph at this PR's head. This comment is informational; the existing **Dependency audit** check remains the gate.",
        "",
        "### Vulnerabilities",
        "",
        *table(vulnerabilities),
    ]

    for kind in KINDS:
        lines.extend(["", f"### {kind.title()} warnings", "", *table(warnings.get(kind, []))])

    lines.extend([
        "",
        "### Reviewed ignores (`deny.toml`)",
        "",
        "| advisory | disposition |",
        "|---|---|",
    ])
    if ignores:
        for ignored in ignores:
            if isinstance(ignored, dict):
                lines.append(f"| {cell(ignored.get('id'))} | {cell(ignored.get('reason'))} |")
            else:
                lines.append(f"| {cell(ignored)} | _No inline reason recorded._ |")
    else:
        lines.append("| — | _None._ |")

    deny_status = sys.argv[3]
    if deny_status != "0":
        notes.append(f"`cargo deny check` exited with status {cell(deny_status)}; see the Dependency audit job log for its full policy diagnostics.")
    if notes:
        lines.extend(["", "> " + " ".join(notes)])
    lines.extend(["", "_Generated by `scripts/audit-pr-comment.sh`._"])
    print("\n".join(lines))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
